name: ci

on: [push]

permissions:
    contents: read

env:
    NODE_VERSION: '24'

jobs:
    lint:
        name: Lint and type-check
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v7

            # TODO: go back to `pnpm/setup@v2` once https://github.com/pnpm/setup/issues/47 is resolved
            - name: Setup pnpm and Node.js
              uses: pnpm/setup@v2.1.0
              with:
                  runtime: node@${{ env.NODE_VERSION }}
                  cache: true
                  require-lockfile: true

            - name: Cache ESLint cache
              uses: actions/cache@v6
              with:
                  path: .cache/.eslintcache
                  # Invalidate cache when any of the listed files changes
                  key: ${{ runner.os }}-eslint-${{ hashFiles('pnpm-lock.yaml', 'eslint.config.js') }}

            - name: Lint the code
              run: pnpm run lint

            - name: Check types
              run: pnpm run check-types

    build:
        name: Build
        uses: ./.github/workflows/build.yml
